### ISSUE TITLE
testing functions with more than one parameter

### ISSUE THREAD

**Issue by martin-flower** [TomerAberbach/pava#1]
Hello - could you provide a configuration example for testing a function with more than one parameter - I guess using an array?

**Comment by TomerAberbach** [comment]
Hey! I just updated the usage examples in the readme. Let me know if that clarifies it

**Comment by martin-flower** [comment]
Thanks for the example - I can get my code to compile, but I don't understand the following error :

 `TypeError: (0 , pava_1.default) is not a function`

**Comment by TomerAberbach** [comment]
Sounds like your build/compilation setup is misconfigured. Can't help with that unfortunately
